CREATE TABLE IF NOT EXISTS pessoa
(
    id_pessoa BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pnome VARCHAR(50),
    minicial VARCHAR(1),
    unome VARCHAR(50),
    nacionalidade VARCHAR(30),
    data_nascimento DATE
    );

CREATE TABLE IF NOT EXISTS serie
(
    id_serie BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(100),
    sinopse VARCHAR(500),
    qtde_temporadas INT,
    genero VARCHAR(50),
    ano_inicio INTEGER,
    ano_fim INTEGER
    );

CREATE TABLE IF NOT EXISTS filme
(
    id_filme BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(100) UNIQUE,
    sinopse VARCHAR(500) UNIQUE,
    genero VARCHAR(50),
    duracao TIME,
    data_lancamento DATE
    );

CREATE TABLE IF NOT EXISTS pessoa_atua_serie
(
    id_pessoa BIGINT,
    id_serie BIGINT,
    funcao VARCHAR(100),
    PRIMARY KEY (id_pessoa, id_serie),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa),
    FOREIGN KEY (id_serie) REFERENCES serie(id_serie)
    );

CREATE TABLE IF NOT EXISTS pessoa_atua_filme
(
    id_pessoa BIGINT,
    id_filme BIGINT,
    funcao VARCHAR(100),
    PRIMARY KEY (id_pessoa, id_filme),
    FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa),
    FOREIGN KEY (id_filme) REFERENCES filme(id_filme)
    );

CREATE TABLE IF NOT EXISTS usuario
(
    id_usuario BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_usuario VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    senha VARCHAR(255),
    status_solicitacao_critico BOOLEAN,
    data_cadastro DATE,
    tipo_usuario VARCHAR(20)
    );

CREATE TABLE IF NOT EXISTS avaliacao
(
    id_avaliacao BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT,
    nota INT,
    comentario VARCHAR(255),
    tipo_conteudo_avaliacao VARCHAR(10),
    data_avaliacao DATE,
    id_conteudo_avaliacao INT,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    );

CREATE TABLE IF NOT EXISTS avaliacao_serie
(
    id_serie BIGINT,
    id_avaliacao BIGINT,
    PRIMARY KEY(id_serie, id_avaliacao),
    FOREIGN KEY (id_serie) REFERENCES serie(id_serie),
    FOREIGN KEY (id_avaliacao) REFERENCES avaliacao(id_avaliacao)
    );

CREATE TABLE IF NOT EXISTS avaliacao_filme
(
    id_filme BIGINT,
    id_avaliacao BIGINT,
    PRIMARY KEY(id_filme, id_avaliacao),
    FOREIGN KEY (id_filme) REFERENCES filme(id_filme),
    FOREIGN KEY (id_avaliacao) REFERENCES avaliacao(id_avaliacao)
    );